export const posts = [
  {
    title: 'The Space Between Confidence and Competence',
    slug: 'the-space-between-confidence-and-competence',
    date: '2026-07-03',
    readTime: '5 min read',
    featured: true,
    excerpt:
      'Confidence is a feeling. Competence is a record of what has already survived contact with reality. I did not understand the difference until I watched something I built almost fail in front of judges.',
    intro:
      'Most of what I know about fear, I learned from machines, not people. A machine cannot fake being ready. It either holds the loop or it does not, and that honesty changed how I think about my own mind.',
    sections: [
      {
        heading: 'The ten seconds after a motor cuts out',
        paragraphs: [
          'At Inter IIT Tech Meet 13.0, our test plan called for cutting power to one motor mid-flight and watching whether the fault-tolerant control we had written could recover the quadrotor and bring it down inside a tight drift window. I knew the math. I had watched it work in simulation dozens of times. None of that stopped my chest from going tight the moment the motor actually died.',
          'There is a specific kind of fear in that gap, the ten seconds between a failure starting and knowing whether the recovery logic will hold. You cannot intervene. Reaching for the controls would only fight the system you spent months tuning. The only thing left to do is watch and find out whether the thing you built is actually true, or whether it just looked true on a screen.',
          'It held. X drift stayed under 0.15 meters, Y drift under 0.30, and the vehicle set down clean. But the feeling that stayed with me was not pride. It was how little my own confidence had to do with the outcome. I had felt ready for weeks. The vehicle did not care what I felt. It only cared what the controller actually did.',
        ],
      },
      {
        heading: 'Confidence is not evidence',
        paragraphs: [
          'Confidence is generated by a brain trying to manage its own fear. It rises and falls based on sleep, on how the last rehearsal went, on whether someone senior is watching. None of that has anything to do with whether a system will actually survive the failure it is about to face.',
          'A control loop does not get a vote. It does not feel good about itself before a test and it does not talk itself into being ready. It either satisfies the conditions that were verified beforehand, or it does not. I started to notice that I trusted that kind of evidence completely, and I trusted my own felt sense of readiness barely at all, and I think that gap is actually correct.',
        ],
      },
      {
        heading: 'Why I stopped trying to feel ready',
        paragraphs: [
          'For a long time I treated the feeling of confidence as something to chase before a hard moment, a test, a presentation, a launch. Chasing a feeling is a bad strategy, because feelings do not track reality closely enough to be useful. Some days I felt ready and was not. Some days I felt shaky and the work held fine.',
          'What actually changed things was building a track record instead of a mood: what had survived simulation, what had survived a bench test, what had survived a partial failure injected on purpose before anyone was watching. Confidence became a byproduct of that record, not something I needed to manufacture in advance. If the evidence was thin, no amount of psyching myself up closed the gap, and I stopped pretending it could.',
        ],
      },
      {
        heading: 'The machine as a mirror',
        paragraphs: [
          'Working with systems that fail without ego changed how I treat my own failures. A drone that crashes is not embarrassed. It does not need to protect a story about itself. The log just says what happened, and the next step is diagnosis, not shame.',
          'I try to read my own mistakes the same way now. A wrong call is a data point about what I had not yet tested in myself, not a verdict on who I am. That reframe did not come from a book. It came from spending enough hours next to systems that treat failure as information, until it started to rub off on how I treat mine.',
        ],
      },
      {
        heading: 'What I actually trust now',
        paragraphs: [
          'I still feel fear before something hard. I do not think that goes away, and I am not sure it should. What changed is what I use to answer it. Not the feeling of being ready, which I have learned not to trust, but the evidence of what has already been tested, in the system and in myself.',
        ],
      },
    ],
  },
  {
    title: 'What Flight Logs Hide',
    slug: 'what-flight-logs-hide',
    date: '2026-07-03',
    readTime: '6 min read',
    featured: true,
    excerpt:
      'A pilot can stare at clean graphs and still miss the failure pattern that matters. I wrote this after building a tool that had to explain logs instead of only plotting them.',
    intro:
      'Flight logs tell the truth, but they do not tell it in a way a tired operator can use. I learned that while working on log analysis products. The graph exists. The explanation does not.',
    sections: [
      {
        heading: 'Graphs do not finish the job',
        paragraphs: [
          'A graph can show oscillation, battery sag, or a motor mismatch. It does not tell you which problem deserves attention first.',
          'That gap matters when someone has one battery left, a field test in an hour, and no time to read six charts in parallel. The log has the answer buried in it somewhere. Finding that answer under time pressure is a different skill than plotting the data, and most tools stop at the plot.',
        ],
      },
      {
        heading: 'A tune problem that looked like wind',
        paragraphs: [
          'One log I worked through had a quadrotor oscillating on the roll axis during a fast forward pass. The easy read was wind. It was a field day, there was a breeze, and the oscillation showed up right when the vehicle picked up speed.',
          'The wind theory fell apart once I lined up the rate-tracking error against the commanded setpoint instead of just looking at attitude. The oscillation frequency stayed constant across passes with different wind headings, but it scaled with forward speed. That is a rate-PID gain fighting a airspeed-dependent aerodynamic term, not gusts. Wind noise is random. This was not.',
          'None of that shows up on a single attitude chart. It shows up when you put rate error, setpoint, and airspeed on the same timeline and ask what actually moves together.',
        ],
      },
      {
        heading: 'Where the signal actually lives',
        paragraphs: [
          'The useful patterns in a log are rarely a single trace. Battery sag on its own is normal. Battery sag that lines up with a specific commanded thrust ramp, every time, on every flight, is a power system finding its limit.',
          'EKF2 innovation spikes are the same story. A spike by itself can be sensor noise. A spike that shows up two or three seconds before every failsafe trigger is a leading indicator, and that timing gap is the difference between a warning an operator can act on and a report written after the crash.',
          'Vibration energy behaves the same way. Raw accelerometer noise is expected on any airframe. Energy concentrated in a narrow band near motor RPM, present on one arm and not the others, is a prop imbalance, and it is diagnosable from the log alone if you decompose the signal instead of eyeballing the raw trace.',
        ],
      },
      {
        heading: 'I care about the next action',
        paragraphs: [
          'I want a system to tell the operator what changed, why it changed, and what to test next.',
          'That is the difference between a debug surface and a usable product. A debug surface hands you the truth in a format that requires expertise to read. A usable product does the correlation work first and hands you a sentence you can act on before the next flight.',
        ],
      },
      {
        heading: 'Explaining beats plotting',
        paragraphs: [
          'This is the reasoning behind Pawaac Analyzer, the log tool I built for PAWAAC Drones. It reads PX4, Betaflight, ArduPilot, and MAVLink logs, extracts the deterministic features first (the sag correlations, the innovation timing, the vibration bands), and only then runs analysis on top of those real values instead of guessing from a chart.',
          'The interface is replay-first. An operator sees the flight happen, sees a tune score, and sees the specific evidence behind that score instead of a folder of graphs. Army and police pilots using it in beta do not have time to interpret six plots between sorties. They have time to read one paragraph that is grounded in the actual signal, and act on it.',
        ],
      },
    ],
  },
  {
    title: 'Building Products from Robotics Habits',
    slug: 'building-products-from-robotics-habits',
    date: '2026-07-03',
    readTime: '5 min read',
    featured: true,
    excerpt:
      'Robotics taught me to respect constraints. That habit changed how I build software products too.',
    intro:
      'Robotics gives you no room for fake confidence. A control loop breaks, a sensor drifts, a mission fails. That pressure changed how I think about product work.',
    sections: [
      {
        heading: 'You learn to respect the full loop',
        paragraphs: [
          'A drone does not care that one subsystem looks elegant. The whole loop has to hold, from sensor read to control output to actuator response, or the vehicle falls out of the sky.',
          'I build software products the same way now. A feature is not done when the screen looks clean. It is done when the user can move through the whole job, from first click to final result, without friction anywhere in that chain.',
        ],
      },
      {
        heading: 'Simulate before you fly',
        paragraphs: [
          'Nobody tunes a controller on the first real flight. You run it in SITL, then Gazebo, then a tethered bench test, and only then a free flight, because every stage catches a class of failure the previous one could not see.',
          'I carry that discipline into software. Staging environments and feature flags are not bureaucracy to me, they are the SITL step. I do not trust my own first real-world run any more than I would trust a controller that has never seen simulation, no matter how confident the code looked while I was writing it.',
        ],
      },
      {
        heading: 'Interfaces matter more than clever parts',
        paragraphs: [
          'Good robotics work depends on clear interfaces between estimation, control, sensors, and mission logic. The EKF does not need to know what the mission planner is doing. The controller does not need to know how the estimate was produced. Each piece trusts a contract, not the internals of its neighbor.',
          'Good product systems depend on the same discipline. When I built ReBloom, scraping, AI orchestration, plan limits, and billing all sit behind their own boundaries. Clean boundaries save you when the product grows, the same way a clean estimator-controller split saves you when you swap in a new sensor without rewriting the flight code around it.',
        ],
      },
      {
        heading: 'Failure has to be a first-class case',
        paragraphs: [
          'Fault-tolerant control starts from the assumption that something will fail, a motor, a sensor, a link, and the system has to have a planned response instead of an improvised one. That mindset does not turn off when I switch to writing product code.',
          'It shows up as designing for partial failures on purpose: what happens when an API call times out mid-request, what an account sees when a usage limit is hit mid-session, what gets retried and what gets surfaced to the user honestly. Happy-path-only code is the software version of a controller that has never been tested against a failure case.',
        ],
      },
      {
        heading: 'The habit that stuck',
        paragraphs: [
          'The one habit from robotics that changed my product work the most is treating confidence as something you earn from a test, not something you assume from a clean-looking implementation. That is a small shift, but it changes almost every decision after it.',
        ],
      },
    ],
  },
  {
    title: 'Why I Care About Operator Workflows',
    slug: 'why-i-care-about-operator-workflows',
    date: '2026-07-03',
    readTime: '5 min read',
    featured: false,
    excerpt:
      'I like hard engineering, but I pay close attention to the person using the system. If the workflow breaks, the system breaks.',
    intro:
      'A product can be technically correct and still be painful to use. I care about the operator view because I have seen smart systems fail at the handoff point.',
    sections: [
      {
        heading: 'The handoff is part of the build',
        paragraphs: [
          'When an operator has to translate a tool in their head before they can use it, the product is unfinished. The engineering can be perfect and the workflow can still fail at the exact moment someone needs it most.',
          'That is why I think about dashboards, forms, playback tools, and alerts with the same seriousness as the backend. A correct system with a confusing handoff is, in practice, an incorrect system.',
        ],
      },
      {
        heading: "A console built for someone else's job",
        paragraphs: [
          'During VTOL transition tuning at PAWAAC Drones, I worked inside QGroundControl on parameters that engineers understand deeply and pilots do not need to think about at all. It is easy to build a console that exposes every parameter the engineering team cares about, because that is the mental model of whoever is building it.',
          'The pilot in the field during a transition does not want a parameter page. They want one number, the airspeed margin before the transition point, and one decision, abort or continue. Getting from "everything the engineer knows" down to "the one thing the pilot needs right now" is most of the actual interface design work, and it happens after the control logic is already correct.',
        ],
      },
      {
        heading: 'A clear path beats a crowded interface',
        paragraphs: [
          'A user usually needs one next move, not ten options.',
          'I build interfaces that expose the right detail at the right time instead of throwing the whole system on the screen at once. Depth should be one click away for the person who wants it, not the default view for the person who does not have time for it.',
        ],
      },
      {
        heading: 'Designing for someone under pressure',
        paragraphs: [
          'Pawaac Analyzer is built around that same idea. Army and police pilots in the beta group are not reviewing logs for fun, they are reviewing them between operational sorties with limited time. Handing them a folder of raw graphs and calling it a product would be technically accurate and practically useless.',
          'The replay-first workflow gives a tune score and a short, evidence-backed next step first, with the raw signal available underneath for anyone who wants to go deeper. The guided path is the product. The graphs are the appendix.',
        ],
      },
      {
        heading: 'The dashboard is not an afterthought',
        paragraphs: [
          'On the fleet operations platform I designed, the live ops dashboard was part of the architecture from the first sketch, not something bolted onto finished backend services. Telemetry ingestion, alerting, and mission planning all exist to feed that one operator-facing surface.',
          'A system that gets the backend right and treats the operator view as decoration will eventually fail at the handoff, no matter how correct the services underneath it are. I would rather start from the screen someone is actually going to be staring at during an incident, and build backward from there.',
        ],
      },
    ],
  },
]
